### ISSUE TITLE
self hosted bot is not posting images

### ISSUE THREAD

**Issue by MrLDasVino** [RayzrDev/Gameboi#15]
I am not sure what I am doing wrong but, the bot has been activated via docker since the link to the jar file is dead, everything seems to be working however the bot isn't posting any images when trying to play a game here is an image 
![Screenshot 2022-12-25 213443](https://user-images.githubusercontent.com/57874812/209481372-243fe576-cd3e-481e-9e6e-b26ca7313cd9.png)
Thanks for any help
edit: permissions do allow the bot to embed and post files so that is not the issue

**Comment by foxfirecodes** [comment]
hey there! i've fixed the Jenkins CI server so you're welcome to download the JAR from there again! as for self-hosting, you'll need to either expose the port that Gameboi's web server runs on to the public web ([port 7000, by default](https://github.com/RayzrDev/Gameboi/blob/main/src/main/resources/config.yml#L6)) or run the bot [behind some kind of reverse proxy, such as `nginx`](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu-22-04) if you want to secure traffic to the bot's webserver with SSL and point a domain name to it

whether you're doing this on a local machine or on a remote server, I highly recommend against _just_ opening the port, as that will expose either your local machine's or your remote server's IP address. the quickest and safest bet is to pick up a cheap domain on [namecheap](https://www.namecheap.com/) or [porkbun](https://porkbun.com/), set it up on a free plan of [https://cloudflare.com/], and point your domain name to your local machine or remote server's IP address _with proxying on_ so that the original IP address is not publicly exposed

from there, it's just a matter of setting up something like nginx (the guide I linked should have you covered) to actually handle the traffic on port 443 and reverse proxy it to Gameboi

while the bot is technically self-hostable, there's a good deal of work necessary to do so now that Gameboi serves images via a web server, so you are of course always welcome to [invite the already hosted version of Gameboi](https://discordapp.com/oauth2/authorize?scope=bot&client_id=593090553856524298&permissions=8192) to your server to use with no hassle :)

if you _do_ want to try and self-host your own version with a domain name, nginx, etc then feel free to [join my discord server](//rayzr.dev/join) and I can help you if you run into any issues!
